### ISSUE TITLE
Cannot startup calico-vpp-node on dpdk interface configuration

### ISSUE THREAD

**Issue by redbag-2** [projectcalico/vpp-dataplane#273]
**Environment**
- Calico/VPP version: master / v0.17.0-calicov3.20.2
- Kubernetes version: 1.19.15-00
- Deployment type: VM
- Network configuration: 
Calico / host-local IPAM? no 
IPIP / VXLAN enabled? no
Specific BGP settings? no

**Issue description**

I used calico-vpp-dpdk.yaml to deploy calico-vpp, and got some errors.
I only modified "vpp_dataplane_interface" value to my interface name on calico-vpp-dpdk.yaml.
![image](https://user-images.githubusercontent.com/67085916/144353912-b5804bc8-00a8-43df-8c9a-24425e698846.png)
![image](https://user-images.githubusercontent.com/67085916/144354273-815744d4-fc99-4d91-b369-9c6b262a919b.png)

I checked calico-vpp-node logs and finded error message.
![image](https://user-images.githubusercontent.com/67085916/144354543-7088824a-6e8d-4fd8-a397-45fc11e71cd7.png)

I using "vppctl" and found the interface was not startup
![image](https://user-images.githubusercontent.com/67085916/144366636-f760d67e-27e3-4ee9-bc52-d377bc793f83.png)

So, I startup this interface and assigned IP addr.
![image](https://user-images.githubusercontent.com/67085916/144367118-b54dafcb-5038-446b-a96b-98135d631d3e.png)

It seemed everything work, but host cannot connect to internet.
![image](https://user-images.githubusercontent.com/67085916/144367290-5975ba7b-4c14-4d15-947e-f4b8f9c796ec.png)
![image](https://user-images.githubusercontent.com/67085916/144367843-f1c45cac-3d84-4d14-870d-73981c4c0600.png)

[agent.log](https://github.com/projectcalico/vpp-dataplane/files/7639506/agent.log)

[vpp.log](https://github.com/projectcalico/vpp-dataplane/files/7639507/vpp.log)

[calico-kube-ctl.log](https://github.com/projectcalico/vpp-dataplane/files/7639508/calico-kube-ctl.log)

Can tell me how to correct startup calico-vpp on dpdk interface configuration?

**To Reproduce**

- Setup huge page
- kubectl apply -f  vpp-dataplane/yaml/generated/calico-vpp-dpdk.yaml

**Additional context**
Calico-vpp v0.16.0-calicov3.20.0 is work well.

**Comment by AloysAugustin** [comment]
Thank you for the detailed report, it seems we introduced an issue in the latest release.
#274 should fix it, we'll provide new images once it is merged.

**Comment by AloysAugustin** [comment]
`prerelease` and `latest` images have been pushed with the fix, please reopen if these don't solve your issue.
