### ISSUE TITLE
GA: Scale issue: directly watching Calico resources 

### ISSUE THREAD

**Issue by fasaxc** [projectcalico/vpp-dataplane#293]
**Environment**
- Calico/VPP version: v0.18.1-calicov3.21.2

**Issue description**

The vpp-dataplane is watching resources in the the Calico API directly.  We found that watching Node resources from every Felix would cause scale issues at the API server with more than 50 nodes.  This is because every kubelet writes to its own Node resource every few seconds; if every node also watches all the nodes then you get the API server doing O(n^2) work.

We added a caching proxy (Typha) to solve that problem. 

**To Reproduce**
 
Create 50+ node cluster; expect to see high CPU usage at API server, growing O(n^2) with number of nodes.

**Comment by fasaxc** [comment]
Copying in slack discussion:

Aloys Augustin Yesterday at 11:46 AM
> That's a great point, thanks. We should probably consider going through Typha as well, because I think in most situations we are watching all the Nodes.

shaun.crampton  1 day ago
> Sadly Typha isn't 100% generic.  Its API exposes a number of "syncer" types.  Syncers are effectively bundles of different watchers, so the "felix syncer" sends events for all the resources that felix is interested in.
Some of options:
Pass the objects you need through felix.  Felix is already watching Nodes and (very recently) kubernetes Services so we could just pass them through on the proto API (if we're not already).  This avoids needing to send the same resource form Typha twice per node.
Use an existing syncer that exposes what you need.  Not sure if there's a good fit: felix syncer will send too much, the confd syncer won't include k8s services.
Add a new syncer.  This is not too hard to do.

Aloys Augustin  1 day ago
> Interesting, passing this data in the proto API through Felix sounds nice. Do you expect the other dataplanes to need this info as well?

Aloys Augustin  1 day ago
> In particular, if we get this through felix, I think it abstracts more of the Calico config from us (do we use Typha or not, what's the endpoint...)

shaun.crampton  1 day ago
> Going down the list of resources, I think Felix is watching most of them already.  Some of them may come through on the proto API already (in some translated form).
Node: felix already watches this in most configurations.  They appear as *proto.RouteUpdate and *proto.VXLANTunnelEndpointUpdate messages (in VXLAN mode).
IP pools, same.  These appear as *proto.RouteUpdate objects on the protobuf API.  (May only be enabled if felix thinks the dataplane needs them.)
IPAM Blocks.  These appear as *proto.RouteUpdate objects on the protobuf API. (May only be enabled if felix thinks the dataplane needs them.)
Felix config, felix certainly watches that (and sends it through as a *proto.ConfigUpdate object IIRC.
BGPPeers, I don't think felix watches these

shaun.crampton  1 day ago
> The route resolver (calculation graph component that outputs the RouteUpdates) is only enabled if certain config is set, to save CPU: https://github.com/projectcalico/calico/blob/master/felix/calc/calc_graph.go#L337

**Comment by fasaxc** [comment]
Another note: I think some of the data you're watching is sent you via the protobuf API.  For example, the config parameters.

**Comment by caseydavenport** [comment]
Remaining watches as of today are:

- BGP config
- IPAM affinity
- BGP peers

These are all low traffic APIs so are OK for GA purposes to call this done.

Would be nice to eventually move these to Typha anyway for better performance, but the Node watch and IPAM block APIs are the worst culprits.
