### ISSUE TITLE
Wildcard host endpoint support

### ISSUE THREAD

**Issue by fasaxc** [projectcalico/vpp-dataplane#299]
**Environment**
- Calico/VPP version: v0.18.1-calicov3.21.2

**Issue description**
I'm not sure if wildcard host endpoints (i.e. host endpoint with name=`"*"` are fully implemented.  they're intended to protect the host from all interfaces, including workload interfaces.  So, for example, ingress pre-DNAT policy can be used to police traffic to node ports and cluster IPs (matching on the node port or the cluster IP) no matter where it comes from: pod->host remote host->local node port etc.

That said, pre-DNAT policy is marked as TODO so I'm wondering if any types of policy that would be affected are currently supported.

**To Reproduce**

Right now, I don't think this policy is enforced in the pod->host direction.

**Expected behavior**
Will see if I can dig out a specification for you...

**Comment by AloysAugustin** [comment]
Hi @fasaxc ,
Wildcard host endpoints should be supported afaik: https://github.com/projectcalico/vpp-dataplane/blob/master/calico-vpp-agent/policy/policy_server.go#L752 
Are there test cases in the calico e2e tests we could run to validate that?

This said, you're correct about pre-DNAT policies not being supported at the moment (as well as untracked policies). How often do you see these two being used?

**Comment by fasaxc** [comment]
I saw some support but I didn't see anything that was policing local pod to host, which is one of the things you can do with wildcard host endpoints.  So, when a local pod connects to its own host, the pod's egress policy and the wildcard hep's ingress policy should both be executed.

pre-DNAT policy with wildcard host endpoints solves an important problem for some users,  It allows you to police traffic to NodePorts at entry to the cluster.  Not super common but important for some users (including some of our larger customers).

**Comment by AloysAugustin** [comment]
We tested blocking pod -> node traffic, it can be done either with the pod egress policy or the host endpoint policy. The pod policy is applied on the pod tun interface, and wildcard host endpoint policies are applied on the tap that goes to the node.
