### ISSUE TITLE
IPSets logic uses O(n^2) loops

### ISSUE THREAD

**Issue by fasaxc** [projectcalico/vpp-dataplane#300]
**Environment**
- Calico/VPP version: v0.18.1-calicov3.21.2
- Kubernetes version: 
- Deployment type: cloud, hosted, VM, bare-metal...
- Network configuration: Calico / host-local IPAM? IPIP / VXLAN enabled? Specific BGP settings?

**Issue description**
Spotted some cases in the IP sets logic where the code may blow up with large IP sets:
```
		for j := 0; j < len(i.Addresses); j++ {
			for _, r := range addrs {
				if i.Addresses[j].Equal(r) {
					i.Addresses[j] = i.Addresses[len(i.Addresses)-1]
					i.Addresses = i.Addresses[:len(i.Addresses)-1]
				}
			}
		}
```
IPSets can contain an entry for every pod in the cluster so you could have 100k entries in an IP set and 100k entries being added/removed.  We generally use a map-based Set implementation to track members in Felix.

**Comment by AloysAugustin** [comment]
This was fixed in #303
