### ISSUE TITLE
Pod creation error

### ISSUE THREAD

**Issue by glazychev-art** [projectcalico/vpp-dataplane#330]
**Environment**
- Calico/VPP version: v0.18.1-calicov3.21.2
- Kubernetes version: v1.21.1
- [NSM](https://github.com/networkservicemesh/deployments-k8s/tree/main/examples/basic)
- kind cluster

**Issue description**
I'm working with [Network Service Mesh examples](https://github.com/networkservicemesh/deployments-k8s/tree/main/examples/basic). In this examples pods are created and deleted multiple times. After 30-40 times - pods are no longer created and I see errors:
`kubectl describe pods -n ns-xxx`:
```
...
Failed to create pod sandbox: rpc error: code = Unknown desc = failed to setup network for sandbox "029b9dbfd7d7f4f94dfba8bd5388f21ccd4de6db3fd543b38e87c369059c1970": grpc dataplane error: Error creating interface: Cannot create interface: Out of buffers: available buffers = 575, buffers needed = 2048. Increase buffers-per-numa in the VPP configuration or reduce CALICOVPP_TAP_RING_SIZE to allow more pods to be scheduled. You may want to limit the number of pods per node to prevent this error
...
```
Full logs:
[describe-ns-428dk.log](https://github.com/projectcalico/vpp-dataplane/files/8060470/describe-ns-428dk.log)

Please, do you have any idea what happened?
Thank you.

**Comment by sknat** [comment]
Hi @glazychev-art ,
This seems to be due to VPP overallocating buffers / creating too many tuns for containers.
This should be solved by #331 
I'll push images with the patch included this evening CET in the images `calicovpp/{agent|node}:latest`

**Comment by glazychev-art** [comment]
@sknat 
Thank you!
Unfortunately I can't test it now. Probably we can close this issue.

**Comment by sknat** [comment]
No worries,
You can test it when you get a testbed, 
we can keep this issue open in the meantime to track it.

**Comment by AloysAugustin** [comment]
Hi @glazychev-art , how many pods are running on the node when you have this issue?

**Comment by glazychev-art** [comment]
Hi @AloysAugustin ,
About 25 pods.

But the problems start after a few tests runs. Initially, everything is fine.
By the time the problems start, pods have been created and deleted about 120-140 times in total.

**Comment by AloysAugustin** [comment]
25 pods should be fine, it could be due to calico/vpp leaking interfaces. Could you run [`calivppctl export`](https://projectcalico.docs.tigera.io/maintenance/troubleshoot/vpp) on your cluster once the problem starts happening and either attach the output archive here or send it to me on Slack?

**Comment by glazychev-art** [comment]
@AloysAugustin 
Sure
[export.tar.gz](https://github.com/projectcalico/vpp-dataplane/files/8132785/export.tar.gz)

**Comment by AloysAugustin** [comment]
There was an issue in the way we accounted for buffers, which should now be fixed.
Could you try with the newest `latest` images and confirm whether they solve the issue?

**Comment by glazychev-art** [comment]
@AloysAugustin 
Yes, I don't see this error anymore.
Thank you!

**Comment by sknat** [comment]
Thanks for reporting & testing @glazychev-art !
I'm closing the issue as #340 seems to fix it.
