### ISSUE TITLE
Do you have any plans to update VPP version?

### ISSUE THREAD

**Issue by glazychev-art** [projectcalico/vpp-dataplane#407]
Hello,
Do you have any plans to update [VPP version](https://github.com/projectcalico/vpp-dataplane/blob/master/vpplink/binapi/vpp_clone_current.sh#L87)? The current is `38659d8f2c588500f4e844195e0c59ab1cf6107f`

I ask because we sometimes see instability - wireguard drops traffic. This happens after creating and deleting several pods (about 50) with creating and deleting ip-interfaces (including wireguard).

And as I see, the latest VPP version contains significant changes in this direction.

Thanks

**Comment by onong** [comment]
Hi @glazychev-art, as of now we do not have any plans to update to the latest version of VPP.

**Comment by sknat** [comment]
Hi @glazychev-art 
As of the merge of #423 we are now targeting VPP from `8b90d89b05322ceaaf57e0eda403c4f92546f7b3` which is after v22.10. We will probably rebase again before releasing v3.25.

Regarding releases, only the images tagged `:latest` and `:prerelease` target this version. The next release to have a newer version of VPP will be 3.25.
