### ISSUE TITLE
af_xdp support

### ISSUE THREAD

**Issue by glazychev-art** [projectcalico/vpp-dataplane#477]
**Environment**
- Calico/VPP version:  v3.24.1
- Kubernetes version: v1.25.3
- Deployment type: kind version 0.17.0
- Network configuration: `vpp_uplink_driver: af_xdp`

**Issue description**
Hi,
I have a question - is `af_xdp` currently supported? When I choose it for `vpp_uplink_driver` I see vpp container logs:
```
time="2022-12-29T07:39:14Z" level=error msg="VPP run failed with Error running VPP: Error creating main interface: Error creating AF_XDP interface: CreateAfXDP failed: req &{HostIf:eth0 Name: RxqNum:8 RxqSize:1024 TxqSize:1024 Mode:AF_XDP_API_MODE_AUTO Flags:AfXdpFlag(0) Prog:} reply &{Retval:-7 SwIfIndex:0}: VPPApiError: Invalid value (-7)"
```
and the Calico pods don't start

**Comment by sknat** [comment]
Hi @glazychev-art 

`af_xdp` should definitely be supported. Looking at the message that triggers the error and the VPP code,
what may trigger an `Invalid value (-7)` is the `RxqNum:8`,  does `eth0` have `8` queues in e.g. `ethtool` ?

**Comment by glazychev-art** [comment]
Thanks for the answer! I will definitely check. 
I think we can close the issue for now.
