### ISSUE TITLE
Failed to deploy Calico VPP 3.25 with error "Error creating uplink interface: error trying to find interface with tag main-ens785f0"

### ISSUE THREAD

**Issue by xiaohui1wang** [projectcalico/vpp-dataplane#544]
Failed to deploy Calico VPP 3.25 with error "**Error creating uplink interface: error trying to find interface with tag main-ens785f0**".

I see this issue is related to below code:
**./vpp-manager/uplink/default.go:93:             return fmt.Errorf("error trying to find interface with tag main-%s", d.spec.InterfaceName)
./vpp-manager/uplink/dpdk.go:168:               return fmt.Errorf("error trying to find interface with tag main-%s", d.spec.InterfaceName)**

Below is part of calico-vpp.yaml, is there any special NIC configuration that I need to set on NIC **ens785f0**?
...
CALICOVPP_INTERFACES: |-
    {
      "maxPodIfSpec": {
        "rx": 10, "tx": 10, "rxqsz": 1024, "txqsz": 1024
      },
      "defaultPodIfSpec": {
        "rx": 1, "tx":1, "isl3": true
      },
      "vppHostTapSpec": {
        "rx": 1, "tx":1, "rxqsz": 1024, "txqsz": 1024, "isl3": false
      },
      **"uplinkInterfaces": [
        {
          "interfaceName": "ens785f0",
          "vppDriver": "dpdk"
        }**
      ]
    }
  CALICOVPP_FEATURE_GATES: |-
    {
      "memifEnabled": true,
      "vclEnabled": false,
      "multinetEnabled": true,
      "srv6Enabled": false,
      "ipsecEnabled": false
    }

**Comment by hedibouattour** [comment]
Hey, 
I can't see any issue in the config you shared.
Can you please share the output of these commands in `vppctl`
`show error`
`show interface tag <the name of your uplink interface in vpp>`

**Comment by xiaohui1wang** [comment]
Since VPP pod has not been deployed successfully at that moment, thus cannot run **vppctl**.
Why is there a prefix "**main-**" when checking if interface exists or not?
-----------------
	if !d.spec.GetIsMain() {
		return fmt.Errorf("%s driver not supported for secondary interfaces", d.name)
	}
	swIfIndex, err := vpp.SearchInterfaceWithTag("main-" + d.spec.InterfaceName)
	if err != nil {
		return fmt.Errorf("error trying to find interface with tag main-%s", d.spec.InterfaceName)
	}
	d.spec.SwIfIndex = swIfIndex
	return nil
}

**Comment by xiaohui1wang** [comment]
This issue can be fixed by adding "**tag main-ens785f0**" in DPDK config, for example,
    dpdk {
      dev __PCI_DEVICE_ID__ { num-rx-queues 1 num-tx-queues 1 **tag main-ens785f0**}
    }
