### ISSUE TITLE
calico-vpp-node is going to crashloop during test-install-calicovpp-srv6 

### ISSUE THREAD

**Issue by chinthagovardhan** [projectcalico/vpp-dataplane#630]
**Environment**
- Calico/VPP version: master,docker.io/calicovpp/vpp@sha256:4ca6223b3d90870c6223994f273ee3376d1e570fed7e68b819b66140fff599da
- Kubernetes version:    v1.22.1
- Deployment type: VM
- Network configuration: Calico VPP Srv6
**Issue description**
Environment is setup using start-test-cluster and installed calico-srv6 using make test-install-calico-srv6.
The calico-vpp-node pods are going to crashloop state. 
The log file shows

`time="2023-08-23T14:41:11Z" level=fatal msg="Error loading configuration: Environment parsing errors : [Failed to parse CALICOVPP_SRV6: {\n  \"policyPool\": \"cafe::/118\",\n  \"localsidPool\": \"fcff::/48\",\n}, defaulting...: invalid character '}' looking for beginning of object key string]"`

**To Reproduce**
```
make install-test-deps
make start-test-cluster
make test-install-calicovpp-srv6
```

**Expected behavior**
calico-vpp-node pods should come to Running state.

**Additional context**
The issue due to an extra comma (,) in the section CALICOVPP_SRV6 of yaml/overlays/test-vagrant-srv6/srv6.yaml

**Comment by sknat** [comment]
Thanks @chinthagovardhan for the bug report & the fix
