### ISSUE TITLE
ElasticSearch failed to set up in k8s with calico vpp

### ISSUE THREAD

**Issue by guoshuxu** [projectcalico/vpp-dataplane#674]
**Environment**
- Calico/VPP version: v3.26.0
- Kubernetes version: v1.28.3
- Deployment type: bare-metal
- Network configuration: Calico VPP w/VXLAN enabled

**Issue description**
ElasticSearch fails:
![image](https://github.com/projectcalico/vpp-dataplane/assets/74895722/975c4321-4fef-4158-9435-59dde3f53b2b)
Check the log:
![image](https://github.com/projectcalico/vpp-dataplane/assets/74895722/a6d0457f-12e4-4efa-bb3f-e3b32bdc3ff6)

It seems that in elasticsearch pod, it can not resolve the public address. Is this caused by VPP route table?
Compared with Calico CNI(w/o VPP), there is no such issue.

**Comment by onong** [comment]
Is it a kind cluster by any chance?

**Comment by guoshuxu** [comment]
It is a k8s cluster on bare-metal created by Kubespray.

**Comment by onong** [comment]
We have not tested any with kubespray.

Does DNS resolution fail from the other pods too? That is, launch a pod in the cluster and check if DNS works?

**Comment by guoshuxu** [comment]
Found the dns problem and close it.
Thanks @onong.

**Comment by guoshuxu** [comment]
Found the dns problem and close it.
Thanks @onong.
