### ISSUE TITLE
Problem with interfaces in calico-vpp-node 

### ISSUE THREAD

**Issue by ThomasJeffers** [projectcalico/vpp-dataplane#702]
Installed calico/vpp-dataplane correctly and there doesn't seem to be an error anywhere. After the installation I plugged two Intel Ethernet Controller X710 for 10GbE SFP+ cables to the host machine (VM) and using vppctl show int in the calico-vpp-node I can confirm that the pod recognized the interfaces:

```
vpp# 
vpp# show int addr
TenGigabitEthernet1b/0/0 (up):
  L3 192.168.1.1/24
TenGigabitEthernet4/0/0 (up):
  L3 192.168.2.1/24
ipip0 (up): 
  unnumbered, use vmxnet3-0/3/0/0
  L3 192.168.104.29/24
local0 (dn):
loop0 (dn):
  L3 10.244.188.49/32 ip4 table-id -775096599 fib-idx 4
loop1 (dn):
  L3 10.244.188.50/32 ip4 table-id 1476291629 fib-idx 6
tap0 (up):
  L3 192.168.104.29/32 ip4 table-id 1013904223 fib-idx 3
tun1 (up): 
  unnumbered, use loop0
  L3 10.244.188.49/32 ip4 table-id -775096599 fib-idx 4
tun2 (up): 
  unnumbered, use loop1
  L3 10.244.188.50/32 ip4 table-id 1476291629 fib-idx 6
vmxnet3-0/3/0/0 (up):
  L3 192.168.104.29/24
```

So I turned the first two interfaces UP and gave them IP addresses but before performing any routing between the two subnets I tried pinging them individually and unlike what I see in ordinary operating systems, the pod can't ping its own interface!

```
vpp# ping 192.168.1.1

Statistics: 5 sent, 0 received, 100% packet loss
vpp# ping 192.168.2.1

Statistics: 5 sent, 0 received, 100% packet loss
vpp# ping 192.168.1.1 source TenGigabitEthernet1b/0/0

Statistics: 5 sent, 0 received, 100% packet loss
vpp# ping 192.168.2.1 source TenGigabitEthernet4/0/0 

Statistics: 5 sent, 0 received, 100% packet loss
```

And then I thought maybe it's because of the other end of the 10G cables! the other ends are connected to another ubuntu VM and is recognized by the OS, so I tried bridging them but doesn't seem to work.

I'm really new to all these stuff and clearly I've missed some important notes and steps but I can't figure out what to do? can someone please help me with this?

**Comment by sknat** [comment]
Hi @ThomasJeffers 
Yeah, this is limitation in VPP, to my knowledge pinging a local interface will not work. 
Not sure why exactly that is, but it's probably related to the way the ping plugin is constructed.
